# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool: MyVM

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'AzureDevOpsRG04ACR'
    repository: 'MyJavaApp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'App Service Connection'
    appType: 'webAppContainer'
    WebAppName: 'TetrisGameApp101'
    DockerNamespace: 'AzureDevOpsRG04ACR'
    DockerRepository: 'AzureDevOpsRG04ACR/tetris:latest'
    DockerImageTag: '1.0'
